apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: blackjack-frontend
  labels:
    app.kubernetes.io/part-of: blackjack
    apps.tanzu.vmware.com/workload-type: server
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
    - name: gitops_server_address
      value: ssh://git@github.com
    - name: gitops_repository_owner
      value: mwright-pivotal
    - name: gitops_repository_name
      value: blackjack-cv-ai-backend-gitops
    - name: gitops_branch
      value: "master"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-python
  source:
    git:
      url: ssh://git@github.com/mwright-pivotal/blackjack-cv-ai-frontend
      ref:
        branch: master
  env:
    - name: AMQP_HOSTNAME
      valueFrom:
        secretKeyRef:
          key: host
          name: edge-inferencing-events-default-user
          optional: true
    - name: AMQP_PORT
      valueFrom:
        secretKeyRef:
          name: edge-inferencing-events-default-user
          key: port
          optional: true
    - name: AMQP_USER
      valueFrom:
        secretKeyRef:
          name: edge-inferencing-events-default-user
          key: username
          optional: true
    - name: AMQP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: edge-inferencing-events-default-user
          key: password
          optional: true
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: edge-inferencing-events
  resources:
    limits:
      # use only if you have required device plugins enabled in your run cluster
      #gpu.intel.com/i915: 1
      #squat.ai/video: 1
